DEBUG 2020-04-12 11:50:11.804 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-04-12 11:50:11.836 UTC: 	 OpenSSl version: OpenSSL 1.0.2h  3 May 2016
DEBUG 2020-04-12 11:50:11.837 UTC: 	 Executing command: 'submit'
DEBUG 2020-04-12 11:50:11.838 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2020-04-12 11:50:11.848 UTC: 	 Checking credentials
DEBUG 2020-04-12 11:50:11.849 UTC: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2020-04-12 11:50:11.849 UTC: 	 Getting proxy life time left
DEBUG 2020-04-12 11:50:12.555 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 43084

 error: 
 retcode : 0
DEBUG 2020-04-12 11:50:13.263 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 43083

 error: 
 retcode : 0
DEBUG 2020-04-12 11:50:13.263 UTC: 	 Proxy lifetime 43084 secs is different from voms extension lifetime 43083 secs for proxy: /tmp/x509up_u107261
DEBUG 2020-04-12 11:50:13.263 UTC: 	 Proxy valid for 11:58:03 hours
INFO 2020-04-12 11:50:13.263 UTC: 	 Will use CRAB configuration file crabConfig_Data_76x_analysis.py
DEBUG 2020-04-12 11:50:13.263 UTC: 	 Loading CRAB configuration file.
ERROR 2020-04-12 11:50:18.008 UTC: 	 Error while loading CRAB configuration:
Failed to retrieve username from SiteDB. Your DN does not seem to be registered in SiteDB.
Details follow:
  Executed command: curl -sS --capath /etc/grid-security/certificates --cert /tmp/x509up_u107261 --key /tmp/x509up_u107261 'https://cmsweb.cern.ch/sitedb/data/prod/whoami'
    Stdout:
      <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
      <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
       <head>
       <title>CMSWEB Error: No such site</title>
       <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
       <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
       <link rel="stylesheet" type="text/css" media="screen" href="/css/cmsweb.css" />
      </head>
      <body>
       <div id="main">
        <div id="top">
         <div class="boxTitle"><img src="/img/title.gif" alt="CMSWEB (title)" /></div>
        </div>
        <div id="middle">
         <div class="boxLinkContainer">
          <h2>No such site</h2>
          <p>The site you requested does not exist. Could we interest you in <a href='/'>anything else</a>?</p>
         </div>
        </div>
        <div id="bottom">
         <div class="boxFooter">&nbsp;</div>
        </div>
       </div>
      </body>
      </html>
      
    Parsed username: 
Note: Make sure you have the correct certificate mapped in SiteDB (you can check what is the certificate you currently have mapped in SiteDB by searching for your name in https://cmsweb.cern.ch/sitedb/prod/people). For instructions on how to map a certificate in SiteDB, see https://twiki.cern.ch/twiki/bin/viewauth/CMS/SiteDBForCRAB.
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-04-12 11:50:18.008 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 320, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
Failed to retrieve username from SiteDB. Your DN does not seem to be registered in SiteDB.
Details follow:
  Executed command: curl -sS --capath /etc/grid-security/certificates --cert /tmp/x509up_u107261 --key /tmp/x509up_u107261 'https://cmsweb.cern.ch/sitedb/data/prod/whoami'
    Stdout:
      <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
      <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
       <head>
       <title>CMSWEB Error: No such site</title>
       <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
       <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
       <link rel="stylesheet" type="text/css" media="screen" href="/css/cmsweb.css" />
      </head>
      <body>
       <div id="main">
        <div id="top">
         <div class="boxTitle"><img src="/img/title.gif" alt="CMSWEB (title)" /></div>
        </div>
        <div id="middle">
         <div class="boxLinkContainer">
          <h2>No such site</h2>
          <p>The site you requested does not exist. Could we interest you in <a href='/'>anything else</a>?</p>
         </div>
        </div>
        <div id="bottom">
         <div class="boxFooter">&nbsp;</div>
        </div>
       </div>
      </body>
      </html>
      
    Parsed username: 
[1mNote[0m: Make sure you have the correct certificate mapped in SiteDB (you can check what is the certificate you currently have mapped in SiteDB by searching for your name in https://cmsweb.cern.ch/sitedb/prod/people). For instructions on how to map a certificate in SiteDB, see https://twiki.cern.ch/twiki/bin/viewauth/CMS/SiteDBForCRAB.
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2020-04-12 15:03:03.605 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-04-12 15:03:03.633 UTC: 	 OpenSSl version: OpenSSL 1.0.2h  3 May 2016
DEBUG 2020-04-12 15:03:03.633 UTC: 	 Executing command: 'status'
DEBUG 2020-04-12 15:03:03.636 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2020-04-12 15:03:03.638 UTC: 	 Error: crab_projects/crab_ESV_Trigger_Run_v2_JetHT_Run2017F-31Mar2018-v1_12April is not a valid CRAB project directory.
ERROR 2020-04-12 15:03:03.638 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 277, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 595, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_ESV_Trigger_Run_v2_JetHT_Run2017F-31Mar2018-v1_12April is not a valid CRAB project directory.
DEBUG 2020-04-12 15:04:06.507 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-04-12 15:04:06.524 UTC: 	 OpenSSl version: OpenSSL 1.0.2h  3 May 2016
DEBUG 2020-04-12 15:04:06.525 UTC: 	 Executing command: 'status'
DEBUG 2020-04-12 15:04:06.525 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2020-04-12 15:04:06.526 UTC: 	 Error: crab_projects/crab_ESV_Trigger_Run_v2_JetHT_Run2017F-31Mar2018-v1_12April is not a valid CRAB project directory.
ERROR 2020-04-12 15:04:06.526 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 277, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 595, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_ESV_Trigger_Run_v2_JetHT_Run2017F-31Mar2018-v1_12April is not a valid CRAB project directory.
DEBUG 2020-04-12 19:05:51.190 UTC: 	 Running on: Linux lxplus739.cern.ch 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-04-12 19:05:51.205 UTC: 	 OpenSSl version: OpenSSL 1.0.2h  3 May 2016
DEBUG 2020-04-12 19:05:51.205 UTC: 	 Executing command: 'submit'
DEBUG 2020-04-12 19:05:51.205 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2020-04-12 19:05:51.214 UTC: 	 Checking credentials
DEBUG 2020-04-12 19:05:51.215 UTC: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2020-04-12 19:05:51.215 UTC: 	 Getting proxy life time left
DEBUG 2020-04-12 19:05:51.920 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 43145

 error: 
 retcode : 0
DEBUG 2020-04-12 19:05:52.528 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 43144

 error: 
 retcode : 0
DEBUG 2020-04-12 19:05:52.528 UTC: 	 Proxy lifetime 43145 secs is different from voms extension lifetime 43144 secs for proxy: /tmp/x509up_u107261
DEBUG 2020-04-12 19:05:52.528 UTC: 	 Proxy valid for 11:59:04 hours
INFO 2020-04-12 19:05:52.528 UTC: 	 Will use CRAB configuration file crabConfig_Data_76x_analysis.py
DEBUG 2020-04-12 19:05:52.528 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-04-12 19:05:52.615 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-04-12 19:05:52.616 UTC: 	 Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW_10_2_18/Trigger/Trigg_data2017_31Mar2018/V2/CMSSW_10_6_2/src/Test/Triggereffi/test/crab_projects/crab_ESV_Trigger_Run_v2_JetHT_Run2017F-31Mar2018-v1_12April' already exists 
Please change the requestName in the config file
ERROR 2020-04-12 19:05:52.616 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 324, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 418, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW_10_2_18/Trigger/Trigg_data2017_31Mar2018/V2/CMSSW_10_6_2/src/Test/Triggereffi/test/crab_projects/crab_ESV_Trigger_Run_v2_JetHT_Run2017F-31Mar2018-v1_12April' already exists 
Please change the requestName in the config file
